### ISSUE TITLE
getting SyntaxError: invalid syntax error

### ISSUE THREAD

**Issue by Gujjugaming2k** [Nunnito/PyWardBot#3]
root@telegram:~/PyWardBot/app# python3 main.py
Traceback (most recent call last):
  File "/root/PyWardBot/app/main.py", line 16, in <module>
    from forward import user
  File "/root/PyWardBot/app/forward.py", line 88
    match message.media:
          ^
SyntaxError: invalid syntax
root@telegram:~/PyWardBot/app#

**Comment by Nunnito** [comment]
Hi, @Gujjugaming2k.

What Python version are you using?

I can see `match message.media` in the traceback. The  `match` keyword  is only available in Python 3.10+.
Maybe you need to upgrade your Python version?
