### ISSUE TITLE
Bot not running - newbie here

### ISSUE THREAD

**Issue by VHCSBlast** [Nunnito/PyWardBot#5]
Hello

I made all the steps, and got "18-10-2023 15:39:02 - main:1209 - INFO: Bot started
18-10-2023 15:39:02 - main:1210 - INFO: Bot username:"

But when I go to telegram, open the bot chat and do /start nothing happens.

What am I doing wrong? 

Thanks in advance

**Comment by Nunnito** [comment]
Hi, VHCSBlast!

Just to know, is the bot username display correctly in the output? Like `INFO: Bot username"@testbot001"`

Also, please open the `PyWardBot/app/config/bot.json` file and check that your Telegram ID is in the `admins` array.
The file should look like this:
```
{
        "api_id": 1234567,
        "api_hash": "0123456789abcdef0123456789abcdef",
        "admins": [your_telegram_id_must_be_here]
}
```

If you don't know how to get you Telegram ID, just chat with the @getidsbot bot. And place you ID there.

If none of this works, please send the log file located in the root folder.

**Comment by VHCSBlast** [comment]
Thank you very much.

The ID was wrong. It was filled automaticly when I run the config.py and I didn't double check.

Now I copied the true ID and it's working. Thank you

**Comment by VHCSBlast** [comment]
Sorry to disturb again, now I'm stuck in this step. 

I forward message from target group and that's ok. But then I forward message from source group and nothing happens. 

The code give me an error in line 23. I tried to close bracket but doesn't help.

Thanks again

![stuck](https://github.com/Nunnito/PyWardBot/assets/106249759/cdc2e6ae-d382-47a6-a05d-c8242285e652)
![stuck2](https://github.com/Nunnito/PyWardBot/assets/106249759/b56e815c-df98-4c77-98a5-ca3cf12b8685)
