### ISSUE TITLE
Sorry to disturb again, now I'm stuck in this step.

### ISSUE THREAD

**Issue by VHCSBlast** [Nunnito/PyWardBot#6]
I forward message from target group and that's ok. But then I forward message from source group and nothing happens. 

The code give me an error in line 23. I tried to close bracket but doesn't help.

Thanks again

![stuck](https://github.com/Nunnito/PyWardBot/assets/106249759/cdc2e6ae-d382-47a6-a05d-c8242285e652)
![stuck2](https://github.com/Nunnito/PyWardBot/assets/106249759/b56e815c-df98-4c77-98a5-ca3cf12b8685)

_Originally posted by @VHCSBlast in https://github.com/Nunnito/PyWardBot/issues/5#issuecomment-1769645479_

**Comment by Nunnito** [comment]
Hi again, VHCSBlast!

That's a really odd error. It seems that the JSON file wasn't closed properly.

You should try to delete the `config/forwarding.json` file and run the bot again. If the issue persists, please let me know!

**Comment by VHCSBlast** [comment]
Hi again,

I deleted the config/forwarding.json file and run the bot again. Error in the same step.

I deleted all the files, and did everything all over again. Now I get a diferent error but in the same step.

When I try to put the source channel the bot stop responding.

Error on LN 23 at forwarding.json.

Can you send me your forwarding.json to chek if I can copy the rest of the code manually and just replace the chat ID?

![erro3](https://github.com/Nunnito/PyWardBot/assets/106249759/87ed4920-13e4-43cd-9ef9-053d87fa0511)

**Comment by Nunnito** [comment]
Could you please send the source and target chat you are entering? I think this is a issue that only occurs on Windows, but I can't replicate it.

And sure, you can see the format of the configuration [here](https://github.com/Nunnito/PyWardBot/blob/cf036617aeeb148de959a7fab0a765c496e0880d/app/config.py#L104).
Mine looks like this:
``` json
{
    "forwarders": [
        {
            "name": "Nunnito",
            "target": 628910404,
            "enabled": true,
            "forwarding_mode": "copy",
            "incoming": true,
            "outgoing": true,
            "reply": true,
            "duplicated_text": false,
            "send_text_only": false,
            "translate": false,
            "translate_to": "en",
            "translate_from": "auto",
            "translate_show_original": false,
            "translate_original_prefix": "Original:",
            "translate_translation_prefix": "Translated:",
            "replace_words_mode": "word_boundary_match",
            "replace_words": {},
            "blocked_words": [],
            "source": {
                "628910404": "Nunnito"
            },
            "patterns": []
        }
    ],
    "blocked_images": []
}
```

**Comment by kalyanbkc123** [comment]
Hi,

i got this message like this how to open the bot.
can u help me.
![Screenshot 2023-10-26 201937](https://github.com/Nunnito/PyWardBot/assets/123096261/3ddf9d68-194a-4f72-b26f-6bf5fc19294b)

**Comment by Nunnito** [comment]
Hey, kalyanbkc123!

What's your issue? To open the bot just send your Telegram bot the command `/start` and you're done!

**Comment by kalyanbkc123** [comment]
Hi, i am a beginner how to launch the bot from where can u help.. tq
