### ISSUE TITLE
Telegram says: [400 PEER_ID_INVALID] - The peer id being used is invalid

### ISSUE THREAD

**Issue by lodha13** [Nunnito/PyWardBot#9]
pyrogram.errors.exceptions.bad_request_400.PeerIdInvalid: Telegram says: [400 PEER_ID_INVALID] - The peer id being used is invalid or not known yet. Make sure you meet the peer before interacting with it 

I am using source as one of the channel from i want to copy the msg to another group. I have captured the id from url after clicking on the that channel. What  am I doing wrong
{
    "forwarders": [
        {
            "name": "test",
            "target": -1002091619145,
            "enabled": true,
            "forwarding_mode": "copy",
            "incoming": true,
            "outgoing": true,
            "reply": true,
            "duplicated_text": false,
            "send_text_only": false,
            "translate": false,
            "translate_to": "en",
            "translate_from": "auto",
            "translate_show_original": false,
            "translate_original_prefix": "Original:",
            "translate_translation_prefix": "Translated:",
            "replace_words_mode": "word_boundary_match",
            "replace_words": {},
            "blocked_words": [],
            "source": {
                "-1001995434407": "test"
            },
            "patterns": []
        }
    ],
    "blocked_images": []	
}

**Comment by Nunnito** [comment]
Hello, lodha13!

I guess the "test" channel is yours. So please send a test message on your "test" channels and try again.

This issue is because the bot's Telegram session doesn't "know" your channel yet. To "know" your channel, the bot session must receive an update from this channel. This can be achieved by sending or receiving a message from this channel.
I hope you understand!

**Comment by lodha13** [comment]
test is random name not the channel name, but after deleting the config files it worked  text msg, I am testing for media+text msg now.

not sure what the use of ("name": "test") in the forwarder, it worked even when the actual channel name was different. Will keep this thread posted on my testing

**Comment by Nunnito** [comment]
I just made commit (9a74e91) that should fix this issue

**Comment by gustavoo779** [comment]
Traceback (most recent call last):
  File "/opt/render/project/src/app/main.py", line 1207, in <module>
    for dialog in user.get_dialogs():
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/pyrogram/sync.py", line 42, in async_to_sync_gen
    item, done = loop.run_until_complete(anext(agen))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/pyrogram/sync.py", line 36, in anext
    return await agen.__anext__(), False
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/pyrogram/methods/chats/get_dialogs.py", line 94, in get_dialogs
    offset_id = last.top_message.id
                ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
it is giving this error
